ALTER TABLE "password" DROP CONSTRAINT IF EXISTS "password_fk0";

ALTER TABLE "follower" DROP CONSTRAINT IF EXISTS "follower_fk0";
ALTER TABLE "follower" DROP CONSTRAINT IF EXISTS "follower_fk1";

DROP TABLE IF EXISTS "user";

DROP TABLE IF EXISTS "password";

DROP TABLE IF EXISTS "post";

DROP TABLE IF EXISTS "follower";

DROP TYPE IF EXISTS "user_roles";
