package config

const NOTIFICATION_LIKE_POST string = "LIKE_POST"
const NOTIFICATION_REPLY_POST string = "REPLY_POST"
const NOTIFICATION_LIKE_REPLY string = "LIKE_REPLY"
const NOTIFICATION_FOLLOW_USER string = "FOLLOW_USER"
const NOTIFICATION_ACCEPT_USER string = "ACCEPT_USER"
