package config

const NOTIFICATION_LIKE_POST string = "LIKE_POST"
const NOTIFICATION_COMMENT_POST string = "COMMENT_POST"
const NOTIFICATION_LIKE_COMMENT string = "LIKE_COMMENT"
const NOTIFICATION_FOLLOW_USER string = "FOLLOW_USER"
const NOTIFICATION_ACCEPT_USER string = "ACCEPT_USER"
