// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: connections.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countFollowersByUserIDAndPageInfo = `-- name: CountFollowersByUserIDAndPageInfo :one
SELECT
	count(*)
FROM
	connections
WHERE
	following_id = $1
	AND status = $2
	AND created_at < $3
	AND deleted_at IS NULL
GROUP BY
	id
ORDER BY
	created_at DESC
LIMIT
	$4
`

type CountFollowersByUserIDAndPageInfoParams struct {
	FollowingID uuid.UUID
	Status      int32
	CreatedAt   time.Time
	Limit       int32
}

func (q *Queries) CountFollowersByUserIDAndPageInfo(ctx context.Context, arg CountFollowersByUserIDAndPageInfoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowersByUserIDAndPageInfo,
		arg.FollowingID,
		arg.Status,
		arg.CreatedAt,
		arg.Limit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowingByUserIDAndPageInfo = `-- name: CountFollowingByUserIDAndPageInfo :one
SELECT
	count(*)
FROM
	connections
WHERE
	follower_id = $1
	AND status = $2
	AND created_at < $3
	AND deleted_at IS NULL
GROUP BY
	id
ORDER BY
	created_at DESC
LIMIT
	$4
`

type CountFollowingByUserIDAndPageInfoParams struct {
	FollowerID uuid.UUID
	Status     int32
	CreatedAt  time.Time
	Limit      int32
}

func (q *Queries) CountFollowingByUserIDAndPageInfo(ctx context.Context, arg CountFollowingByUserIDAndPageInfoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowingByUserIDAndPageInfo,
		arg.FollowerID,
		arg.Status,
		arg.CreatedAt,
		arg.Limit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConnection = `-- name: CreateConnection :one
INSERT INTO
	connections (following_id, follower_id, status)
VALUES
	($1, $2, $3) RETURNING id, follower_id, following_id, status, created_at, updated_at, deleted_at
`

type CreateConnectionParams struct {
	FollowingID uuid.UUID
	FollowerID  uuid.UUID
	Status      int32
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (*Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection, arg.FollowingID, arg.FollowerID, arg.Status)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteConnection = `-- name: DeleteConnection :one
UPDATE
	connections
SET
	deleted_at = $1
WHERE
	id = $2 RETURNING id, follower_id, following_id, status, created_at, updated_at, deleted_at
`

type DeleteConnectionParams struct {
	DeletedAt sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (*Connection, error) {
	row := q.db.QueryRowContext(ctx, deleteConnection, arg.DeletedAt, arg.ID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getConnection = `-- name: GetConnection :one
SELECT
	id, follower_id, following_id, status, created_at, updated_at, deleted_at
FROM
	connections
WHERE
	following_id = $1
	AND follower_id = $2
	AND deleted_at IS NULL
`

type GetConnectionParams struct {
	FollowingID uuid.UUID
	FollowerID  uuid.UUID
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (*Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, arg.FollowingID, arg.FollowerID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT
	id, follower_id, following_id, status, created_at, updated_at, deleted_at
FROM
	connections
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetConnectionByID(ctx context.Context, id uuid.UUID) (*Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getConnectionsByIDs = `-- name: GetConnectionsByIDs :many
SELECT
	id, follower_id, following_id, status, created_at, updated_at, deleted_at
FROM
	connections
WHERE
	id = ANY($1 :: uuid [ ])
	AND deleted_at IS NULL
`

func (q *Queries) GetConnectionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*Connection, error) {
	rows, err := q.db.QueryContext(ctx, getConnectionsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.FollowerID,
			&i.FollowingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersByUserIDAndPageInfo = `-- name: GetFollowersByUserIDAndPageInfo :many
SELECT
	id, follower_id, following_id, status, created_at, updated_at, deleted_at
FROM
	connections
WHERE
	following_id = $1
	AND status = $2
	AND created_at < $3
	AND deleted_at IS NULL
GROUP BY
	id
ORDER BY
	created_at DESC
LIMIT
	$4
`

type GetFollowersByUserIDAndPageInfoParams struct {
	FollowingID uuid.UUID
	Status      int32
	CreatedAt   time.Time
	Limit       int32
}

func (q *Queries) GetFollowersByUserIDAndPageInfo(ctx context.Context, arg GetFollowersByUserIDAndPageInfoParams) ([]*Connection, error) {
	rows, err := q.db.QueryContext(ctx, getFollowersByUserIDAndPageInfo,
		arg.FollowingID,
		arg.Status,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.FollowerID,
			&i.FollowingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingByUserIDAndPageInfo = `-- name: GetFollowingByUserIDAndPageInfo :many
SELECT
	id, follower_id, following_id, status, created_at, updated_at, deleted_at
FROM
	connections
WHERE
	follower_id = $1
	AND status = $2
	AND created_at < $3
	AND deleted_at IS NULL
GROUP BY
	id
ORDER BY
	created_at DESC
LIMIT
	$4
`

type GetFollowingByUserIDAndPageInfoParams struct {
	FollowerID uuid.UUID
	Status     int32
	CreatedAt  time.Time
	Limit      int32
}

func (q *Queries) GetFollowingByUserIDAndPageInfo(ctx context.Context, arg GetFollowingByUserIDAndPageInfoParams) ([]*Connection, error) {
	rows, err := q.db.QueryContext(ctx, getFollowingByUserIDAndPageInfo,
		arg.FollowerID,
		arg.Status,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.FollowerID,
			&i.FollowingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE
	connections
SET
	status = $1
WHERE
	follower_id = $2
	AND following_id = $3
	AND deleted_at IS NULL RETURNING id, follower_id, following_id, status, created_at, updated_at, deleted_at
`

type UpdateConnectionParams struct {
	Status      int32
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (*Connection, error) {
	row := q.db.QueryRowContext(ctx, updateConnection, arg.Status, arg.FollowerID, arg.FollowingID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
