// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: credit_transaction_templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCreditTransactionTemplateByID = `-- name: GetCreditTransactionTemplateByID :one
SELECT
	id, name, amount, content, deleted_at
FROM
	credit_transaction_templates
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetCreditTransactionTemplateByID(ctx context.Context, id uuid.UUID) (*CreditTransactionTemplate, error) {
	row := q.db.QueryRowContext(ctx, getCreditTransactionTemplateByID, id)
	var i CreditTransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Content,
		&i.DeletedAt,
	)
	return &i, err
}

const getCreditTransactionTemplateByName = `-- name: GetCreditTransactionTemplateByName :one
SELECT
	id, name, amount, content, deleted_at
FROM
	credit_transaction_templates
WHERE
	NAME = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetCreditTransactionTemplateByName(ctx context.Context, name CreditTransactionTemplateName) (*CreditTransactionTemplate, error) {
	row := q.db.QueryRowContext(ctx, getCreditTransactionTemplateByName, name)
	var i CreditTransactionTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Content,
		&i.DeletedAt,
	)
	return &i, err
}
