// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: credit_transactions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCreditTransactionsByUserIDAndPageInfo = `-- name: CountCreditTransactionsByUserIDAndPageInfo :one
WITH _count_wrapper AS (
	SELECT
		count(*)
	FROM
		credit_transactions AS credit_transaction
		INNER JOIN credit_transaction_infos ON credit_transaction_infos.id = credit_transaction.credit_transaction_info_id
	WHERE
		credit_transaction.user_id = $1
		AND credit_transaction_infos.created_at < $2
		AND credit_transaction.deleted_at IS NULL
	GROUP BY
		credit_transaction.id,
		credit_transaction_infos.id,
		credit_transaction_infos.created_at
	ORDER BY
		credit_transaction_infos.created_at DESC
)
SELECT
	count(*)
FROM
	_count_wrapper
`

type CountCreditTransactionsByUserIDAndPageInfoParams struct {
	UserID    pgtype.UUID
	CreatedAt time.Time
}

func (q *Queries) CountCreditTransactionsByUserIDAndPageInfo(ctx context.Context, arg CountCreditTransactionsByUserIDAndPageInfoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditTransactionsByUserIDAndPageInfo, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreditTransaction = `-- name: CreateCreditTransaction :one
INSERT INTO
	credit_transactions (
		user_id,
		recipient_id,
		amount,
		credit_transaction_info_id,
		TYPE,
		url
	)
VALUES
	($1, $2, $3, $4, $5, $6) RETURNING id, user_id, recipient_id, relevant_credit_transaction_id, credit_transaction_info_id, amount, url, type, created_at, deleted_at
`

type CreateCreditTransactionParams struct {
	UserID                  pgtype.UUID
	RecipientID             pgtype.UUID
	Amount                  float32
	CreditTransactionInfoID pgtype.UUID
	Type                    CreditTransactionType
	Url                     string
}

func (q *Queries) CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (*CreditTransaction, error) {
	row := q.db.QueryRow(ctx, createCreditTransaction,
		arg.UserID,
		arg.RecipientID,
		arg.Amount,
		arg.CreditTransactionInfoID,
		arg.Type,
		arg.Url,
	)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientID,
		&i.RelevantCreditTransactionID,
		&i.CreditTransactionInfoID,
		&i.Amount,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getCreditTransactionByID = `-- name: GetCreditTransactionByID :one
SELECT
	id, user_id, recipient_id, relevant_credit_transaction_id, credit_transaction_info_id, amount, url, type, created_at, deleted_at
FROM
	credit_transactions
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetCreditTransactionByID(ctx context.Context, id pgtype.UUID) (*CreditTransaction, error) {
	row := q.db.QueryRow(ctx, getCreditTransactionByID, id)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientID,
		&i.RelevantCreditTransactionID,
		&i.CreditTransactionInfoID,
		&i.Amount,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getCreditTransactionByUrl = `-- name: GetCreditTransactionByUrl :one
SELECT
	id, user_id, recipient_id, relevant_credit_transaction_id, credit_transaction_info_id, amount, url, type, created_at, deleted_at
FROM
	credit_transactions
WHERE
	url = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetCreditTransactionByUrl(ctx context.Context, url string) (*CreditTransaction, error) {
	row := q.db.QueryRow(ctx, getCreditTransactionByUrl, url)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecipientID,
		&i.RelevantCreditTransactionID,
		&i.CreditTransactionInfoID,
		&i.Amount,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getCreditTransactionsByUserIDAndPageInfo = `-- name: GetCreditTransactionsByUserIDAndPageInfo :many
SELECT
	credit_transaction.id, user_id, recipient_id, relevant_credit_transaction_id, credit_transaction_info_id, amount, url, type, credit_transaction.created_at, credit_transaction.deleted_at, credit_transaction_infos.id, credit_transaction_template_id, description, status, credit_transaction_infos.created_at, updated_at, credit_transaction_infos.deleted_at
FROM
	credit_transactions AS credit_transaction
	INNER JOIN credit_transaction_infos ON credit_transaction_infos.id = credit_transaction.credit_transaction_info_id
WHERE
	credit_transaction.user_id = $1
	AND credit_transaction_infos.created_at < $2
	AND credit_transaction.deleted_at IS NULL
ORDER BY
	credit_transaction_infos.created_at DESC
LIMIT
	$3
`

type GetCreditTransactionsByUserIDAndPageInfoParams struct {
	UserID    pgtype.UUID
	CreatedAt time.Time
	Limit     int32
}

type GetCreditTransactionsByUserIDAndPageInfoRow struct {
	ID                          pgtype.UUID
	UserID                      pgtype.UUID
	RecipientID                 pgtype.UUID
	RelevantCreditTransactionID pgtype.UUID
	CreditTransactionInfoID     pgtype.UUID
	Amount                      float32
	Url                         string
	Type                        CreditTransactionType
	CreatedAt                   time.Time
	DeletedAt                   *time.Time
	ID_2                        pgtype.UUID
	CreditTransactionTemplateID pgtype.UUID
	Description                 pgtype.Text
	Status                      CreditTransactionStatus
	CreatedAt_2                 time.Time
	UpdatedAt                   time.Time
	DeletedAt_2                 *time.Time
}

func (q *Queries) GetCreditTransactionsByUserIDAndPageInfo(ctx context.Context, arg GetCreditTransactionsByUserIDAndPageInfoParams) ([]*GetCreditTransactionsByUserIDAndPageInfoRow, error) {
	rows, err := q.db.Query(ctx, getCreditTransactionsByUserIDAndPageInfo, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetCreditTransactionsByUserIDAndPageInfoRow{}
	for rows.Next() {
		var i GetCreditTransactionsByUserIDAndPageInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecipientID,
			&i.RelevantCreditTransactionID,
			&i.CreditTransactionInfoID,
			&i.Amount,
			&i.Url,
			&i.Type,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ID_2,
			&i.CreditTransactionTemplateID,
			&i.Description,
			&i.Status,
			&i.CreatedAt_2,
			&i.UpdatedAt,
			&i.DeletedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreditsByUserID = `-- name: GetCreditsByUserID :one
SELECT
	sum(credit_transaction.amount) AS amount
FROM
	credit_transactions AS credit_transaction
	INNER JOIN credit_transaction_infos ON credit_transaction_infos.id = credit_transaction.credit_transaction_info_id
WHERE
	credit_transaction.user_id = $1
	AND credit_transaction_infos.status = 'approved'
	AND credit_transaction.deleted_at IS NULL
`

func (q *Queries) GetCreditsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getCreditsByUserID, userID)
	var amount int64
	err := row.Scan(&amount)
	return amount, err
}
