// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: files.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createFile = `-- name: CreateFile :one
INSERT INTO
	files (NAME, hash, width, height)
VALUES
	($1, $2, $3, $4) RETURNING id, hash, name, width, height, created_at, updated_at, deleted_at
`

type CreateFileParams struct {
	Name   string
	Hash   string
	Width  int32
	Height int32
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (*File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Name,
		arg.Hash,
		arg.Width,
		arg.Height,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getFileByHash = `-- name: GetFileByHash :one
SELECT
	id, hash, name, width, height, created_at, updated_at, deleted_at
FROM
	files
WHERE
	hash = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetFileByHash(ctx context.Context, hash string) (*File, error) {
	row := q.db.QueryRowContext(ctx, getFileByHash, hash)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT
	id, hash, name, width, height, created_at, updated_at, deleted_at
FROM
	files
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (*File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getFileByName = `-- name: GetFileByName :one
SELECT
	id, hash, name, width, height, created_at, updated_at, deleted_at
FROM
	files
WHERE
	NAME = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetFileByName(ctx context.Context, name string) (*File, error) {
	row := q.db.QueryRowContext(ctx, getFileByName, name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getFilesByPostID = `-- name: GetFilesByPostID :many
SELECT
	file.id, file.hash, file.name, file.width, file.height, file.created_at, file.updated_at, file.deleted_at
FROM
	files AS file
	INNER JOIN post_attachments ON post_attachments.file_id = file.id
WHERE
	post_attachments.post_id = $1
	AND file.deleted_at IS NULL
	AND post_attachments.deleted_at IS NULL
GROUP BY
	file.id
`

func (q *Queries) GetFilesByPostID(ctx context.Context, postID uuid.UUID) ([]*File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByPostIDs = `-- name: GetFilesByPostIDs :many
SELECT
	file.id, file.hash, file.name, file.width, file.height, file.created_at, file.updated_at, file.deleted_at,
	post_attachments.post_id
FROM
	files AS file
	INNER JOIN post_attachments ON post_attachments.file_id = file.id
WHERE
	post_attachments.post_id = ANY($1 :: uuid [ ])
	AND file.deleted_at IS NULL
	AND post_attachments.deleted_at IS NULL
GROUP BY
	file.id,
	post_attachments.post_id
`

type GetFilesByPostIDsRow struct {
	ID        uuid.UUID
	Hash      string
	Name      string
	Width     int32
	Height    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	PostID    uuid.UUID
}

func (q *Queries) GetFilesByPostIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]*GetFilesByPostIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByPostIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetFilesByPostIDsRow{}
	for rows.Next() {
		var i GetFilesByPostIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByTicketMessageID = `-- name: GetFilesByTicketMessageID :many
SELECT
	file.id, file.hash, file.name, file.width, file.height, file.created_at, file.updated_at, file.deleted_at
FROM
	files AS file
	INNER JOIN ticket_message_attachments ON ticket_message_attachments.file_id = file.id
WHERE
	ticket_message_attachments.ticket_message_id = $1
	AND file.deleted_at IS NULL
	AND ticket_message_attachments.deleted_at IS NULL
GROUP BY
	file.id
`

func (q *Queries) GetFilesByTicketMessageID(ctx context.Context, ticketMessageID uuid.UUID) ([]*File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByTicketMessageID, ticketMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
