// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: invited_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO
	invited_users (inviter_id, invitee_id)
VALUES
	($1, $2) RETURNING id, inviter_id, invitee_id, status, created_at, updated_at, deleted_at
`

type CreateInvitedUserParams struct {
	InviterID uuid.UUID
	InviteeID uuid.UUID
}

func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (*InvitedUser, error) {
	row := q.db.QueryRowContext(ctx, createInvitedUser, arg.InviterID, arg.InviteeID)
	var i InvitedUser
	err := row.Scan(
		&i.ID,
		&i.InviterID,
		&i.InviteeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
