// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type BackgroundColor string

const (
	BackgroundColorLight BackgroundColor = "light"
	BackgroundColorDim   BackgroundColor = "dim"
	BackgroundColorDark  BackgroundColor = "dark"
)

func (e *BackgroundColor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BackgroundColor(s)
	case string:
		*e = BackgroundColor(s)
	default:
		return fmt.Errorf("unsupported scan type for BackgroundColor: %T", src)
	}
	return nil
}

type NullBackgroundColor struct {
	BackgroundColor BackgroundColor
	Valid           bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBackgroundColor) Scan(value interface{}) error {
	if value == nil {
		ns.BackgroundColor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BackgroundColor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBackgroundColor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.BackgroundColor, nil
}

type CreditTransactionDescriptionVariableKey string

const (
	CreditTransactionDescriptionVariableKeyInvitedUser CreditTransactionDescriptionVariableKey = "invited_user"
	CreditTransactionDescriptionVariableKeyInviterUser CreditTransactionDescriptionVariableKey = "inviter_user"
	CreditTransactionDescriptionVariableKeyTicket      CreditTransactionDescriptionVariableKey = "ticket"
)

func (e *CreditTransactionDescriptionVariableKey) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionDescriptionVariableKey(s)
	case string:
		*e = CreditTransactionDescriptionVariableKey(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionDescriptionVariableKey: %T", src)
	}
	return nil
}

type NullCreditTransactionDescriptionVariableKey struct {
	CreditTransactionDescriptionVariableKey CreditTransactionDescriptionVariableKey
	Valid                                   bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionDescriptionVariableKey) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionDescriptionVariableKey, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionDescriptionVariableKey.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionDescriptionVariableKey) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.CreditTransactionDescriptionVariableKey, nil
}

type CreditTransactionDescriptionVariableType string

const (
	CreditTransactionDescriptionVariableTypeUser   CreditTransactionDescriptionVariableType = "user"
	CreditTransactionDescriptionVariableTypeTag    CreditTransactionDescriptionVariableType = "tag"
	CreditTransactionDescriptionVariableTypeTicket CreditTransactionDescriptionVariableType = "ticket"
)

func (e *CreditTransactionDescriptionVariableType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionDescriptionVariableType(s)
	case string:
		*e = CreditTransactionDescriptionVariableType(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionDescriptionVariableType: %T", src)
	}
	return nil
}

type NullCreditTransactionDescriptionVariableType struct {
	CreditTransactionDescriptionVariableType CreditTransactionDescriptionVariableType
	Valid                                    bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionDescriptionVariableType) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionDescriptionVariableType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionDescriptionVariableType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionDescriptionVariableType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.CreditTransactionDescriptionVariableType, nil
}

type CreditTransactionStatus string

const (
	CreditTransactionStatusApproved CreditTransactionStatus = "approved"
	CreditTransactionStatusPending  CreditTransactionStatus = "pending"
	CreditTransactionStatusFailed   CreditTransactionStatus = "failed"
	CreditTransactionStatusCanceled CreditTransactionStatus = "canceled"
)

func (e *CreditTransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionStatus(s)
	case string:
		*e = CreditTransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionStatus: %T", src)
	}
	return nil
}

type NullCreditTransactionStatus struct {
	CreditTransactionStatus CreditTransactionStatus
	Valid                   bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.CreditTransactionStatus, nil
}

type CreditTransactionTemplateName string

const (
	CreditTransactionTemplateNameInviteUser               CreditTransactionTemplateName = "invite_user"
	CreditTransactionTemplateNameRegisterByInvitationCode CreditTransactionTemplateName = "register_by_invitation_code"
	CreditTransactionTemplateNameApproveTicket            CreditTransactionTemplateName = "approve_ticket"
)

func (e *CreditTransactionTemplateName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionTemplateName(s)
	case string:
		*e = CreditTransactionTemplateName(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionTemplateName: %T", src)
	}
	return nil
}

type NullCreditTransactionTemplateName struct {
	CreditTransactionTemplateName CreditTransactionTemplateName
	Valid                         bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionTemplateName) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionTemplateName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionTemplateName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionTemplateName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.CreditTransactionTemplateName, nil
}

type CreditTransactionType string

const (
	CreditTransactionTypeOrder      CreditTransactionType = "order"
	CreditTransactionTypeTransfer   CreditTransactionType = "transfer"
	CreditTransactionTypeCommission CreditTransactionType = "commission"
	CreditTransactionTypeFund       CreditTransactionType = "fund"
)

func (e *CreditTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionType(s)
	case string:
		*e = CreditTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionType: %T", src)
	}
	return nil
}

type NullCreditTransactionType struct {
	CreditTransactionType CreditTransactionType
	Valid                 bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.CreditTransactionType, nil
}

type CreditTransactionTypeName string

const (
	CreditTransactionTypeNameInviteUser               CreditTransactionTypeName = "invite_user"
	CreditTransactionTypeNameRegisterByInvitationCode CreditTransactionTypeName = "register_by_invitation_code"
)

func (e *CreditTransactionTypeName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionTypeName(s)
	case string:
		*e = CreditTransactionTypeName(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionTypeName: %T", src)
	}
	return nil
}

type NullCreditTransactionTypeName struct {
	CreditTransactionTypeName CreditTransactionTypeName
	Valid                     bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionTypeName) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionTypeName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionTypeName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionTypeName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.CreditTransactionTypeName, nil
}

type InvitedUserStatus string

const (
	InvitedUserStatusRegistered InvitedUserStatus = "registered"
	InvitedUserStatusPosted     InvitedUserStatus = "posted"
)

func (e *InvitedUserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitedUserStatus(s)
	case string:
		*e = InvitedUserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitedUserStatus: %T", src)
	}
	return nil
}

type NullInvitedUserStatus struct {
	InvitedUserStatus InvitedUserStatus
	Valid             bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitedUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitedUserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitedUserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitedUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.InvitedUserStatus, nil
}

type NotificationTypeName string

const (
	NotificationTypeNameWelcome       NotificationTypeName = "welcome"
	NotificationTypeNameLikePost      NotificationTypeName = "like_post"
	NotificationTypeNameReplyPost     NotificationTypeName = "reply_post"
	NotificationTypeNameLikeReply     NotificationTypeName = "like_reply"
	NotificationTypeNameAcceptUser    NotificationTypeName = "accept_user"
	NotificationTypeNameFollowUser    NotificationTypeName = "follow_user"
	NotificationTypeNameMentionInPost NotificationTypeName = "mention_in_post"
)

func (e *NotificationTypeName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTypeName(s)
	case string:
		*e = NotificationTypeName(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTypeName: %T", src)
	}
	return nil
}

type NullNotificationTypeName struct {
	NotificationTypeName NotificationTypeName
	Valid                bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTypeName) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTypeName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTypeName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTypeName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.NotificationTypeName, nil
}

type PostStatus string

const (
	PostStatusPublic  PostStatus = "public"
	PostStatusPrivate PostStatus = "private"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus
	Valid      bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.PostStatus, nil
}

type PrimaryColor string

const (
	PrimaryColorBlue   PrimaryColor = "blue"
	PrimaryColorGreen  PrimaryColor = "green"
	PrimaryColorRed    PrimaryColor = "red"
	PrimaryColorPurple PrimaryColor = "purple"
	PrimaryColorOrange PrimaryColor = "orange"
	PrimaryColorYellow PrimaryColor = "yellow"
)

func (e *PrimaryColor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrimaryColor(s)
	case string:
		*e = PrimaryColor(s)
	default:
		return fmt.Errorf("unsupported scan type for PrimaryColor: %T", src)
	}
	return nil
}

type NullPrimaryColor struct {
	PrimaryColor PrimaryColor
	Valid        bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrimaryColor) Scan(value interface{}) error {
	if value == nil {
		ns.PrimaryColor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrimaryColor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrimaryColor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.PrimaryColor, nil
}

type TicketStatusType string

const (
	TicketStatusTypeOpen     TicketStatusType = "open"
	TicketStatusTypeClosed   TicketStatusType = "closed"
	TicketStatusTypeApproved TicketStatusType = "approved"
	TicketStatusTypeSolved   TicketStatusType = "solved"
	TicketStatusTypeAccepted TicketStatusType = "accepted"
	TicketStatusTypeRejected TicketStatusType = "rejected"
)

func (e *TicketStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatusType(s)
	case string:
		*e = TicketStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatusType: %T", src)
	}
	return nil
}

type NullTicketStatusType struct {
	TicketStatusType TicketStatusType
	Valid            bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.TicketStatusType, nil
}

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleAdmin      UserRole = "admin"
	UserRoleSuperAdmin UserRole = "super_admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if String is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.UserRole, nil
}

type Connection struct {
	ID          uuid.UUID
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
	Status      int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type CreditTransaction struct {
	ID                          uuid.UUID
	UserID                      uuid.UUID
	RecipientID                 uuid.UUID
	RelevantCreditTransactionID uuid.NullUUID
	CreditTransactionInfoID     uuid.UUID
	Amount                      float32
	Url                         string
	Type                        CreditTransactionType
	CreatedAt                   time.Time
	DeletedAt                   sql.NullTime
}

type CreditTransactionDescriptionVariable struct {
	ID                      uuid.UUID
	CreditTransactionInfoID uuid.UUID
	ContentID               uuid.UUID
	Key                     CreditTransactionDescriptionVariableKey
	Type                    CreditTransactionDescriptionVariableType
	CreatedAt               time.Time
	DeletedAt               sql.NullTime
}

type CreditTransactionInfo struct {
	ID                          uuid.UUID
	CreditTransactionTemplateID uuid.NullUUID
	Description                 sql.NullString
	Status                      CreditTransactionStatus
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	DeletedAt                   sql.NullTime
}

type CreditTransactionTemplate struct {
	ID        uuid.UUID
	Name      CreditTransactionTemplateName
	Amount    sql.NullFloat64
	Content   string
	DeletedAt sql.NullTime
}

type File struct {
	ID        uuid.UUID
	Hash      string
	Name      string
	Width     int32
	Height    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type InvitedUser struct {
	ID        uuid.UUID
	InviterID uuid.UUID
	InviteeID uuid.UUID
	Status    InvitedUserStatus
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type LikedPost struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Notification struct {
	ID                 uuid.UUID
	NotificationTypeID uuid.UUID
	SenderID           uuid.UUID
	ReceiverID         uuid.UUID
	PostID             uuid.NullUUID
	ReplyID            uuid.NullUUID
	Url                string
	Read               bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          sql.NullTime
}

type NotificationType struct {
	ID        uuid.UUID
	Name      NotificationTypeName
	Template  string
	DeletedAt sql.NullTime
}

type OnlineUser struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SocketID  string
	Token     string
	UserAgent string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Password struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Post struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ParentID  uuid.NullUUID
	ChildID   uuid.NullUUID
	Status    PostStatus
	Content   sql.NullString
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type PostAttachment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	FileID    uuid.UUID
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type PostMention struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type PostTag struct {
	ID        uuid.UUID
	TagID     uuid.UUID
	PostID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type SavedPost struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Tag struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Ticket struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Subject   string
	Status    TicketStatusType
	Url       sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type TicketMessage struct {
	ID        uuid.UUID
	TicketID  uuid.UUID
	SenderID  uuid.UUID
	Message   string
	Read      bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type TicketMessageAttachment struct {
	ID              uuid.UUID
	TicketMessageID uuid.UUID
	FileID          uuid.UUID
	CreatedAt       time.Time
	DeletedAt       sql.NullTime
}

type User struct {
	ID              uuid.UUID
	Username        string
	Email           string
	FullName        string
	Bio             sql.NullString
	Role            UserRole
	IsPrivate       bool
	Avatar          uuid.NullUUID
	Background      uuid.NullUUID
	PrimaryColor    PrimaryColor
	BackgroundColor BackgroundColor
	IsVerified      bool
	InvitationCode  string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}
