// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BackgroundColor string

const (
	BackgroundColorLight BackgroundColor = "light"
	BackgroundColorDim   BackgroundColor = "dim"
	BackgroundColorDark  BackgroundColor = "dark"
)

func (e *BackgroundColor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BackgroundColor(s)
	case string:
		*e = BackgroundColor(s)
	default:
		return fmt.Errorf("unsupported scan type for BackgroundColor: %T", src)
	}
	return nil
}

type NullBackgroundColor struct {
	BackgroundColor BackgroundColor
	Valid           bool // Valid is true if BackgroundColor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBackgroundColor) Scan(value interface{}) error {
	if value == nil {
		ns.BackgroundColor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BackgroundColor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBackgroundColor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BackgroundColor), nil
}

type CreditTransactionDescriptionVariableKey string

const (
	CreditTransactionDescriptionVariableKeyInvitedUser CreditTransactionDescriptionVariableKey = "invited_user"
	CreditTransactionDescriptionVariableKeyInviterUser CreditTransactionDescriptionVariableKey = "inviter_user"
	CreditTransactionDescriptionVariableKeyTicket      CreditTransactionDescriptionVariableKey = "ticket"
)

func (e *CreditTransactionDescriptionVariableKey) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionDescriptionVariableKey(s)
	case string:
		*e = CreditTransactionDescriptionVariableKey(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionDescriptionVariableKey: %T", src)
	}
	return nil
}

type NullCreditTransactionDescriptionVariableKey struct {
	CreditTransactionDescriptionVariableKey CreditTransactionDescriptionVariableKey
	Valid                                   bool // Valid is true if CreditTransactionDescriptionVariableKey is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionDescriptionVariableKey) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionDescriptionVariableKey, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionDescriptionVariableKey.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionDescriptionVariableKey) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditTransactionDescriptionVariableKey), nil
}

type CreditTransactionDescriptionVariableType string

const (
	CreditTransactionDescriptionVariableTypeUser   CreditTransactionDescriptionVariableType = "user"
	CreditTransactionDescriptionVariableTypeTag    CreditTransactionDescriptionVariableType = "tag"
	CreditTransactionDescriptionVariableTypeTicket CreditTransactionDescriptionVariableType = "ticket"
)

func (e *CreditTransactionDescriptionVariableType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionDescriptionVariableType(s)
	case string:
		*e = CreditTransactionDescriptionVariableType(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionDescriptionVariableType: %T", src)
	}
	return nil
}

type NullCreditTransactionDescriptionVariableType struct {
	CreditTransactionDescriptionVariableType CreditTransactionDescriptionVariableType
	Valid                                    bool // Valid is true if CreditTransactionDescriptionVariableType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionDescriptionVariableType) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionDescriptionVariableType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionDescriptionVariableType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionDescriptionVariableType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditTransactionDescriptionVariableType), nil
}

type CreditTransactionStatus string

const (
	CreditTransactionStatusApproved CreditTransactionStatus = "approved"
	CreditTransactionStatusPending  CreditTransactionStatus = "pending"
	CreditTransactionStatusFailed   CreditTransactionStatus = "failed"
	CreditTransactionStatusCanceled CreditTransactionStatus = "canceled"
)

func (e *CreditTransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionStatus(s)
	case string:
		*e = CreditTransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionStatus: %T", src)
	}
	return nil
}

type NullCreditTransactionStatus struct {
	CreditTransactionStatus CreditTransactionStatus
	Valid                   bool // Valid is true if CreditTransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditTransactionStatus), nil
}

type CreditTransactionTemplateName string

const (
	CreditTransactionTemplateNameInviteUser               CreditTransactionTemplateName = "invite_user"
	CreditTransactionTemplateNameRegisterByInvitationCode CreditTransactionTemplateName = "register_by_invitation_code"
	CreditTransactionTemplateNameApproveTicket            CreditTransactionTemplateName = "approve_ticket"
)

func (e *CreditTransactionTemplateName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionTemplateName(s)
	case string:
		*e = CreditTransactionTemplateName(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionTemplateName: %T", src)
	}
	return nil
}

type NullCreditTransactionTemplateName struct {
	CreditTransactionTemplateName CreditTransactionTemplateName
	Valid                         bool // Valid is true if CreditTransactionTemplateName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionTemplateName) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionTemplateName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionTemplateName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionTemplateName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditTransactionTemplateName), nil
}

type CreditTransactionType string

const (
	CreditTransactionTypeOrder      CreditTransactionType = "order"
	CreditTransactionTypeTransfer   CreditTransactionType = "transfer"
	CreditTransactionTypeCommission CreditTransactionType = "commission"
	CreditTransactionTypeFund       CreditTransactionType = "fund"
)

func (e *CreditTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionType(s)
	case string:
		*e = CreditTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionType: %T", src)
	}
	return nil
}

type NullCreditTransactionType struct {
	CreditTransactionType CreditTransactionType
	Valid                 bool // Valid is true if CreditTransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditTransactionType), nil
}

type CreditTransactionTypeName string

const (
	CreditTransactionTypeNameInviteUser               CreditTransactionTypeName = "invite_user"
	CreditTransactionTypeNameRegisterByInvitationCode CreditTransactionTypeName = "register_by_invitation_code"
)

func (e *CreditTransactionTypeName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditTransactionTypeName(s)
	case string:
		*e = CreditTransactionTypeName(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditTransactionTypeName: %T", src)
	}
	return nil
}

type NullCreditTransactionTypeName struct {
	CreditTransactionTypeName CreditTransactionTypeName
	Valid                     bool // Valid is true if CreditTransactionTypeName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditTransactionTypeName) Scan(value interface{}) error {
	if value == nil {
		ns.CreditTransactionTypeName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditTransactionTypeName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditTransactionTypeName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditTransactionTypeName), nil
}

type InvitedUserStatus string

const (
	InvitedUserStatusRegistered InvitedUserStatus = "registered"
	InvitedUserStatusPosted     InvitedUserStatus = "posted"
)

func (e *InvitedUserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitedUserStatus(s)
	case string:
		*e = InvitedUserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitedUserStatus: %T", src)
	}
	return nil
}

type NullInvitedUserStatus struct {
	InvitedUserStatus InvitedUserStatus
	Valid             bool // Valid is true if InvitedUserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitedUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitedUserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitedUserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitedUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitedUserStatus), nil
}

type NotificationTypeName string

const (
	NotificationTypeNameWelcome       NotificationTypeName = "welcome"
	NotificationTypeNameLikePost      NotificationTypeName = "like_post"
	NotificationTypeNameReplyPost     NotificationTypeName = "reply_post"
	NotificationTypeNameLikeReply     NotificationTypeName = "like_reply"
	NotificationTypeNameAcceptUser    NotificationTypeName = "accept_user"
	NotificationTypeNameFollowUser    NotificationTypeName = "follow_user"
	NotificationTypeNameMentionInPost NotificationTypeName = "mention_in_post"
)

func (e *NotificationTypeName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTypeName(s)
	case string:
		*e = NotificationTypeName(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTypeName: %T", src)
	}
	return nil
}

type NullNotificationTypeName struct {
	NotificationTypeName NotificationTypeName
	Valid                bool // Valid is true if NotificationTypeName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTypeName) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTypeName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTypeName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTypeName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTypeName), nil
}

type PostStatus string

const (
	PostStatusPublic  PostStatus = "public"
	PostStatusPrivate PostStatus = "private"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus
	Valid      bool // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type PrimaryColor string

const (
	PrimaryColorBlue   PrimaryColor = "blue"
	PrimaryColorGreen  PrimaryColor = "green"
	PrimaryColorRed    PrimaryColor = "red"
	PrimaryColorPurple PrimaryColor = "purple"
	PrimaryColorOrange PrimaryColor = "orange"
	PrimaryColorYellow PrimaryColor = "yellow"
)

func (e *PrimaryColor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrimaryColor(s)
	case string:
		*e = PrimaryColor(s)
	default:
		return fmt.Errorf("unsupported scan type for PrimaryColor: %T", src)
	}
	return nil
}

type NullPrimaryColor struct {
	PrimaryColor PrimaryColor
	Valid        bool // Valid is true if PrimaryColor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrimaryColor) Scan(value interface{}) error {
	if value == nil {
		ns.PrimaryColor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrimaryColor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrimaryColor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrimaryColor), nil
}

type TicketStatusType string

const (
	TicketStatusTypeOpen     TicketStatusType = "open"
	TicketStatusTypeClosed   TicketStatusType = "closed"
	TicketStatusTypeApproved TicketStatusType = "approved"
	TicketStatusTypeSolved   TicketStatusType = "solved"
	TicketStatusTypeAccepted TicketStatusType = "accepted"
	TicketStatusTypeRejected TicketStatusType = "rejected"
)

func (e *TicketStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatusType(s)
	case string:
		*e = TicketStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatusType: %T", src)
	}
	return nil
}

type NullTicketStatusType struct {
	TicketStatusType TicketStatusType
	Valid            bool // Valid is true if TicketStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatusType), nil
}

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleAdmin      UserRole = "admin"
	UserRoleSuperAdmin UserRole = "super_admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Connection struct {
	ID          pgtype.UUID
	FollowerID  pgtype.UUID
	FollowingID pgtype.UUID
	Status      int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type CreditTransaction struct {
	ID                          pgtype.UUID
	UserID                      pgtype.UUID
	RecipientID                 pgtype.UUID
	RelevantCreditTransactionID pgtype.UUID
	CreditTransactionInfoID     pgtype.UUID
	Amount                      float32
	Url                         string
	Type                        CreditTransactionType
	CreatedAt                   time.Time
	DeletedAt                   *time.Time
}

type CreditTransactionDescriptionVariable struct {
	ID                      pgtype.UUID
	CreditTransactionInfoID pgtype.UUID
	ContentID               pgtype.UUID
	Key                     CreditTransactionDescriptionVariableKey
	Type                    CreditTransactionDescriptionVariableType
	CreatedAt               time.Time
	DeletedAt               *time.Time
}

type CreditTransactionInfo struct {
	ID                          pgtype.UUID
	CreditTransactionTemplateID pgtype.UUID
	Description                 pgtype.Text
	Status                      CreditTransactionStatus
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	DeletedAt                   *time.Time
}

type CreditTransactionTemplate struct {
	ID        pgtype.UUID
	Name      CreditTransactionTemplateName
	Amount    pgtype.Float4
	Content   string
	DeletedAt *time.Time
}

type File struct {
	ID        pgtype.UUID
	Hash      string
	Name      string
	Width     int32
	Height    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type InvitedUser struct {
	ID        pgtype.UUID
	InviterID pgtype.UUID
	InviteeID pgtype.UUID
	Status    InvitedUserStatus
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type LikedPost struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	PostID    pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Notification struct {
	ID                 pgtype.UUID
	NotificationTypeID pgtype.UUID
	SenderID           pgtype.UUID
	ReceiverID         pgtype.UUID
	PostID             pgtype.UUID
	ReplyID            pgtype.UUID
	Url                string
	Read               bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
}

type NotificationType struct {
	ID        pgtype.UUID
	Name      NotificationTypeName
	Template  string
	DeletedAt *time.Time
}

type OnlineUser struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	SocketID  string
	Token     string
	UserAgent string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Password struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Post struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ParentID  pgtype.UUID
	ChildID   pgtype.UUID
	Status    PostStatus
	Content   pgtype.Text
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type PostAttachment struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	FileID    pgtype.UUID
	CreatedAt time.Time
	DeletedAt *time.Time
}

type PostMention struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt time.Time
	DeletedAt *time.Time
}

type PostTag struct {
	ID        pgtype.UUID
	TagID     pgtype.UUID
	PostID    pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type SavedPost struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	PostID    pgtype.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Ticket struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Subject   string
	Status    TicketStatusType
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type TicketMessage struct {
	ID        pgtype.UUID
	TicketID  pgtype.UUID
	SenderID  pgtype.UUID
	Message   string
	Read      bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type TicketMessageAttachment struct {
	ID              pgtype.UUID
	TicketMessageID pgtype.UUID
	FileID          pgtype.UUID
	CreatedAt       time.Time
	DeletedAt       *time.Time
}

type User struct {
	ID              pgtype.UUID
	Username        string
	Email           string
	FullName        string
	Bio             pgtype.Text
	Role            UserRole
	IsPrivate       bool
	Avatar          pgtype.UUID
	Background      pgtype.UUID
	PrimaryColor    PrimaryColor
	BackgroundColor BackgroundColor
	IsVerified      bool
	InvitationCode  string
	Settings        UserSettings
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}
