// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByReceiverIDAndPageInfo = `-- name: CountNotificationsByReceiverIDAndPageInfo :one
WITH _count_wrapper AS (
	SELECT
		count(*)
	FROM
		notifications
	WHERE
		receiver_id = $1
		AND deleted_at IS NULL
		AND created_at < $2
)
SELECT
	count(*)
FROM
	_count_wrapper
`

type CountNotificationsByReceiverIDAndPageInfoParams struct {
	ReceiverID pgtype.UUID
	CreatedAt  time.Time
}

func (q *Queries) CountNotificationsByReceiverIDAndPageInfo(ctx context.Context, arg CountNotificationsByReceiverIDAndPageInfoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByReceiverIDAndPageInfo, arg.ReceiverID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotificationsByReceiverID = `-- name: CountUnreadNotificationsByReceiverID :one
WITH _count_wrapper AS (
	SELECT
		count(*)
	FROM
		notifications
	WHERE
		receiver_id = $1
		AND READ = FALSE
		AND deleted_at IS NULL
)
SELECT
	count(*)
FROM
	_count_wrapper
`

func (q *Queries) CountUnreadNotificationsByReceiverID(ctx context.Context, receiverID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsByReceiverID, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO
	notifications (
		notification_type_id,
		sender_id,
		receiver_id,
		deleted_at,
		post_id,
		reply_id,
		url
	)
VALUES
	($1, $2, $3, $4, $5, $6, $7) RETURNING id, notification_type_id, sender_id, receiver_id, post_id, reply_id, url, read, created_at, updated_at, deleted_at
`

type CreateNotificationParams struct {
	NotificationTypeID pgtype.UUID
	SenderID           pgtype.UUID
	ReceiverID         pgtype.UUID
	DeletedAt          *time.Time
	PostID             pgtype.UUID
	ReplyID            pgtype.UUID
	Url                string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (*Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.NotificationTypeID,
		arg.SenderID,
		arg.ReceiverID,
		arg.DeletedAt,
		arg.PostID,
		arg.ReplyID,
		arg.Url,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.NotificationTypeID,
		&i.SenderID,
		&i.ReceiverID,
		&i.PostID,
		&i.ReplyID,
		&i.Url,
		&i.Read,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getNotification = `-- name: GetNotification :one
SELECT
	id, notification_type_id, sender_id, receiver_id, post_id, reply_id, url, read, created_at, updated_at, deleted_at
FROM
	notifications
WHERE
	notification_type_id = $1
	AND sender_id = $2
	AND receiver_id = $3
	AND post_id = $4
	AND reply_id = $5
	AND url = $6
	AND deleted_at IS NULL
LIMIT
	1
`

type GetNotificationParams struct {
	NotificationTypeID pgtype.UUID
	SenderID           pgtype.UUID
	ReceiverID         pgtype.UUID
	PostID             pgtype.UUID
	ReplyID            pgtype.UUID
	Url                string
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (*Notification, error) {
	row := q.db.QueryRow(ctx, getNotification,
		arg.NotificationTypeID,
		arg.SenderID,
		arg.ReceiverID,
		arg.PostID,
		arg.ReplyID,
		arg.Url,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.NotificationTypeID,
		&i.SenderID,
		&i.ReceiverID,
		&i.PostID,
		&i.ReplyID,
		&i.Url,
		&i.Read,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT
	id, notification_type_id, sender_id, receiver_id, post_id, reply_id, url, read, created_at, updated_at, deleted_at
FROM
	notifications
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (*Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.NotificationTypeID,
		&i.SenderID,
		&i.ReceiverID,
		&i.PostID,
		&i.ReplyID,
		&i.Url,
		&i.Read,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getNotificationsByReceiverIDAndPageInfo = `-- name: GetNotificationsByReceiverIDAndPageInfo :many
SELECT
	id, notification_type_id, sender_id, receiver_id, post_id, reply_id, url, read, created_at, updated_at, deleted_at
FROM
	notifications
WHERE
	receiver_id = $1
	AND deleted_at IS NULL
	AND created_at < $2
ORDER BY
	created_at DESC
LIMIT
	$3
`

type GetNotificationsByReceiverIDAndPageInfoParams struct {
	ReceiverID pgtype.UUID
	CreatedAt  time.Time
	Limit      int32
}

func (q *Queries) GetNotificationsByReceiverIDAndPageInfo(ctx context.Context, arg GetNotificationsByReceiverIDAndPageInfoParams) ([]*Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByReceiverIDAndPageInfo, arg.ReceiverID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.NotificationTypeID,
			&i.SenderID,
			&i.ReceiverID,
			&i.PostID,
			&i.ReplyID,
			&i.Url,
			&i.Read,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNotification = `-- name: RemoveNotification :one
UPDATE
	notifications
SET
	deleted_at = $1
WHERE
	notification_type_id = $2
	AND sender_id = $3
	AND receiver_id = $4
	AND post_id = $5
	AND reply_id = $6
	AND deleted_at IS NULL RETURNING id, notification_type_id, sender_id, receiver_id, post_id, reply_id, url, read, created_at, updated_at, deleted_at
`

type RemoveNotificationParams struct {
	DeletedAt          *time.Time
	NotificationTypeID pgtype.UUID
	SenderID           pgtype.UUID
	ReceiverID         pgtype.UUID
	PostID             pgtype.UUID
	ReplyID            pgtype.UUID
}

func (q *Queries) RemoveNotification(ctx context.Context, arg RemoveNotificationParams) (*Notification, error) {
	row := q.db.QueryRow(ctx, removeNotification,
		arg.DeletedAt,
		arg.NotificationTypeID,
		arg.SenderID,
		arg.ReceiverID,
		arg.PostID,
		arg.ReplyID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.NotificationTypeID,
		&i.SenderID,
		&i.ReceiverID,
		&i.PostID,
		&i.ReplyID,
		&i.Url,
		&i.Read,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const removePostNotificationsByPostID = `-- name: RemovePostNotificationsByPostID :many
UPDATE
	notifications
SET
	deleted_at = $1
WHERE
	post_id = $2
	AND deleted_at IS NULL RETURNING id, notification_type_id, sender_id, receiver_id, post_id, reply_id, url, read, created_at, updated_at, deleted_at
`

type RemovePostNotificationsByPostIDParams struct {
	DeletedAt *time.Time
	PostID    pgtype.UUID
}

func (q *Queries) RemovePostNotificationsByPostID(ctx context.Context, arg RemovePostNotificationsByPostIDParams) ([]*Notification, error) {
	rows, err := q.db.Query(ctx, removePostNotificationsByPostID, arg.DeletedAt, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.NotificationTypeID,
			&i.SenderID,
			&i.ReceiverID,
			&i.PostID,
			&i.ReplyID,
			&i.Url,
			&i.Read,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReadNotifications = `-- name: UpdateReadNotifications :many
UPDATE
	notifications
SET
	READ = TRUE
WHERE
	receiver_id = $1
	AND deleted_at IS NULL RETURNING id, notification_type_id, sender_id, receiver_id, post_id, reply_id, url, read, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateReadNotifications(ctx context.Context, receiverID pgtype.UUID) ([]*Notification, error) {
	rows, err := q.db.Query(ctx, updateReadNotifications, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.NotificationTypeID,
			&i.SenderID,
			&i.ReceiverID,
			&i.PostID,
			&i.ReplyID,
			&i.Url,
			&i.Read,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
