// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: post_mentions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPostMention = `-- name: CreatePostMention :one
INSERT INTO
	post_mentions (user_id, post_id)
VALUES
	($1, $2) RETURNING id, post_id, user_id, created_at, deleted_at
`

type CreatePostMentionParams struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
}

func (q *Queries) CreatePostMention(ctx context.Context, arg CreatePostMentionParams) (*PostMention, error) {
	row := q.db.QueryRow(ctx, createPostMention, arg.UserID, arg.PostID)
	var i PostMention
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deletePostMention = `-- name: DeletePostMention :many
UPDATE
	post_mentions
SET
	deleted_at = $1
WHERE
	user_id = $2
	AND post_id = $3
	AND deleted_at IS NULL RETURNING id, post_id, user_id, created_at, deleted_at
`

type DeletePostMentionParams struct {
	DeletedAt *time.Time
	UserID    pgtype.UUID
	PostID    pgtype.UUID
}

func (q *Queries) DeletePostMention(ctx context.Context, arg DeletePostMentionParams) ([]*PostMention, error) {
	rows, err := q.db.Query(ctx, deletePostMention, arg.DeletedAt, arg.UserID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PostMention{}
	for rows.Next() {
		var i PostMention
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePostMentionsByPostID = `-- name: DeletePostMentionsByPostID :many
UPDATE
	post_mentions
SET
	deleted_at = $1
WHERE
	post_id = $2
	AND deleted_at IS NULL RETURNING id, post_id, user_id, created_at, deleted_at
`

type DeletePostMentionsByPostIDParams struct {
	DeletedAt *time.Time
	PostID    pgtype.UUID
}

func (q *Queries) DeletePostMentionsByPostID(ctx context.Context, arg DeletePostMentionsByPostIDParams) ([]*PostMention, error) {
	rows, err := q.db.Query(ctx, deletePostMentionsByPostID, arg.DeletedAt, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PostMention{}
	for rows.Next() {
		var i PostMention
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
