// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
	users (email, username, invitation_code, full_name)
VALUES
	($1, $2, $3, $4) RETURNING id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email          string
	Username       string
	InvitationCode string
	FullName       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.InvitationCode,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
	id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
FROM
	users
WHERE
	lower(email) = lower($1)
	AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
	id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
FROM
	users
WHERE
	id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByInvitationCode = `-- name: GetUserByInvitationCode :one
SELECT
	id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
FROM
	users
WHERE
	lower(invitation_code) = lower($1)
	AND deleted_at IS NULL
`

func (q *Queries) GetUserByInvitationCode(ctx context.Context, lower string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByInvitationCode, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
	id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
FROM
	users
WHERE
	lower(username) = lower($1)
	AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT
	id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
FROM
	users
WHERE
	(
		lower(email) = lower($1)
		OR lower(username) = lower($1)
	)
	AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, lower string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT
	id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
FROM
	users
WHERE
	id = ANY($1 :: uuid [ ])
	AND deleted_at IS NULL
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]*User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Bio,
			&i.Role,
			&i.IsPrivate,
			&i.Avatar,
			&i.Background,
			&i.PrimaryColor,
			&i.BackgroundColor,
			&i.IsVerified,
			&i.InvitationCode,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByUsernameOrFullNameAndPageInfo = `-- name: GetUsersByUsernameOrFullNameAndPageInfo :many
SELECT
	id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
FROM
	users
WHERE
	(
		lower(email) LIKE lower($1)
		OR lower(username) LIKE lower($1)
	)
	AND deleted_at IS NULL
LIMIT
	$2
`

type GetUsersByUsernameOrFullNameAndPageInfoParams struct {
	Lower string
	Limit int32
}

func (q *Queries) GetUsersByUsernameOrFullNameAndPageInfo(ctx context.Context, arg GetUsersByUsernameOrFullNameAndPageInfoParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, getUsersByUsernameOrFullNameAndPageInfo, arg.Lower, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Bio,
			&i.Role,
			&i.IsPrivate,
			&i.Avatar,
			&i.Background,
			&i.PrimaryColor,
			&i.BackgroundColor,
			&i.IsVerified,
			&i.InvitationCode,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE
	users
SET
	username = $2,
	email = $3,
	bio = $4,
	full_name = $5,
	background = $6,
	avatar = $7,
	background_color = $8,
	primary_color = $9,
	is_private = $10
WHERE
	id = $1
	AND deleted_at IS NULL RETURNING id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID              pgtype.UUID
	Username        string
	Email           string
	Bio             pgtype.Text
	FullName        string
	Background      pgtype.UUID
	Avatar          pgtype.UUID
	BackgroundColor BackgroundColor
	PrimaryColor    PrimaryColor
	IsPrivate       bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Bio,
		arg.FullName,
		arg.Background,
		arg.Avatar,
		arg.BackgroundColor,
		arg.PrimaryColor,
		arg.IsPrivate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE
	users
SET
	settings = $2
WHERE
	id = $1
	AND deleted_at IS NULL RETURNING id, username, email, full_name, bio, role, is_private, avatar, background, primary_color, background_color, is_verified, invitation_code, settings, created_at, updated_at, deleted_at
`

type UpdateUserSettingsParams struct {
	ID       pgtype.UUID
	Settings UserSettings
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings, arg.ID, arg.Settings)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Role,
		&i.IsPrivate,
		&i.Avatar,
		&i.Background,
		&i.PrimaryColor,
		&i.BackgroundColor,
		&i.IsVerified,
		&i.InvitationCode,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
