package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"context"
	"fmt"

	"github.com/plogto/core/graph/model"
)

// GetInvitedUsers is the resolver for the getInvitedUsers field.
func (r *queryResolver) GetInvitedUsers(ctx context.Context, pageInfo *model.PageInfoInput) (*model.InvitedUsers, error) {
	panic(fmt.Errorf("not implemented: GetInvitedUsers - getInvitedUsers"))
}
