package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/plogto/core/graph/generated"
	"github.com/plogto/core/graph/model"
	"github.com/plogto/core/util"
)

// User is the resolver for the user field.
func (r *likedPostResolver) User(ctx context.Context, obj *model.LikedPost) (*model.User, error) {
	return r.Service.GetUserByID(ctx, obj.UserID)
}

// Post is the resolver for the post field.
func (r *likedPostResolver) Post(ctx context.Context, obj *model.LikedPost) (*model.Post, error) {
	return r.Service.GetPostByID(ctx, &obj.PostID)
}

// Cursor is the resolver for the cursor field.
func (r *likedPostsEdgeResolver) Cursor(ctx context.Context, obj *model.LikedPostsEdge) (string, error) {
	return util.ConvertCreateAtToCursor(*obj.Node.CreatedAt), nil
}

// Node is the resolver for the node field.
func (r *likedPostsEdgeResolver) Node(ctx context.Context, obj *model.LikedPostsEdge) (*model.LikedPost, error) {
	return r.Service.GetLikedPostByID(ctx, &obj.Node.ID)
}

// LikePost is the resolver for the likePost field.
func (r *mutationResolver) LikePost(ctx context.Context, postID string) (*model.LikedPost, error) {
	return r.Service.LikePost(ctx, postID)
}

// GetLikedPostsByPostID is the resolver for the getLikedPostsByPostId field.
func (r *queryResolver) GetLikedPostsByPostID(ctx context.Context, postID string, pageInfo *model.PageInfoInput) (*model.LikedPosts, error) {
	return r.Service.GetLikedPostsByPostID(ctx, postID)
}

// GetLikedPostsByUsername is the resolver for the getLikedPostsByUsername field.
func (r *queryResolver) GetLikedPostsByUsername(ctx context.Context, username string, pageInfo *model.PageInfoInput) (*model.LikedPosts, error) {
	return r.Service.GetLikedPostsByUsername(ctx, username, pageInfo)
}

// LikedPost returns generated.LikedPostResolver implementation.
func (r *Resolver) LikedPost() generated.LikedPostResolver { return &likedPostResolver{r} }

// LikedPostsEdge returns generated.LikedPostsEdgeResolver implementation.
func (r *Resolver) LikedPostsEdge() generated.LikedPostsEdgeResolver {
	return &likedPostsEdgeResolver{r}
}

type likedPostResolver struct{ *Resolver }
type likedPostsEdgeResolver struct{ *Resolver }
