package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"github.com/plogto/core/db"
	"github.com/plogto/core/graph/generated"
	"github.com/plogto/core/graph/model"
)

// EditUserSettings is the resolver for the editUserSettings field.
func (r *mutationResolver) EditUserSettings(ctx context.Context, input model.EditUserSettingsInput) (*db.User, error) {
	return r.Service.EditUserSettings(ctx, input)
}

// IsRepliesVisible is the resolver for the isRepliesVisible field.
func (r *userSettingsResolver) IsRepliesVisible(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.IsRepliesVisible), nil
}

// IsMediaVisible is the resolver for the isMediaVisible field.
func (r *userSettingsResolver) IsMediaVisible(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.IsMediaVisible), nil
}

// IsLikesVisible is the resolver for the isLikesVisible field.
func (r *userSettingsResolver) IsLikesVisible(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.IsLikesVisible), nil
}

// UserSettings returns generated.UserSettingsResolver implementation.
func (r *Resolver) UserSettings() generated.UserSettingsResolver { return &userSettingsResolver{r} }

type userSettingsResolver struct{ *Resolver }
