package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"github.com/plogto/core/constants"
	"github.com/plogto/core/db"
	"github.com/plogto/core/graph/generated"
	"github.com/plogto/core/graph/model"
	"github.com/plogto/core/validation"
)

// EditUser is the resolver for the editUser field.
func (r *mutationResolver) EditUser(ctx context.Context, input model.EditUserInput) (*db.User, error) {
	return r.Service.EditUser(ctx, input)
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePasswordInput) (*model.AuthResponse, error) {
	return r.Service.ChangePassword(ctx, input)
}

// GetUserInfo is the resolver for the getUserInfo field.
func (r *queryResolver) GetUserInfo(ctx context.Context) (*db.User, error) {
	return r.Service.GetUserInfo(ctx)
}

// GetUserByUsername is the resolver for the getUserByUsername field.
func (r *queryResolver) GetUserByUsername(ctx context.Context, username string) (*db.User, error) {
	return r.Service.GetUserByUsername(ctx, username)
}

// GetUserByInvitationCode is the resolver for the getUserByInvitationCode field.
func (r *queryResolver) GetUserByInvitationCode(ctx context.Context, invitationCode string) (*db.User, error) {
	return r.Service.GetUserByInvitationCode(ctx, invitationCode)
}

// CheckUsername is the resolver for the checkUsername field.
func (r *queryResolver) CheckUsername(ctx context.Context, username string) (*db.User, error) {
	return r.Service.CheckUsername(ctx, username)
}

// CheckEmail is the resolver for the checkEmail field.
func (r *queryResolver) CheckEmail(ctx context.Context, email string) (*db.User, error) {
	return r.Service.CheckEmail(ctx, email)
}

// BackgroundColor is the resolver for the backgroundColor field.
func (r *userResolver) BackgroundColor(ctx context.Context, obj *db.User) (model.BackgroundColor, error) {
	return model.BackgroundColor(obj.BackgroundColor), nil
}

// PrimaryColor is the resolver for the primaryColor field.
func (r *userResolver) PrimaryColor(ctx context.Context, obj *db.User) (model.PrimaryColor, error) {
	return model.PrimaryColor(obj.PrimaryColor), nil
}

// Avatar is the resolver for the avatar field.
func (r *userResolver) Avatar(ctx context.Context, obj *db.User) (*db.File, error) {
	if obj.Avatar.Valid {
		return r.Service.GetFileByFileId(ctx, obj.Avatar)
	} else {
		return nil, nil
	}
}

// Background is the resolver for the background field.
func (r *userResolver) Background(ctx context.Context, obj *db.User) (*db.File, error) {
	if obj.Background.Valid {
		return r.Service.GetFileByFileId(ctx, obj.Background)
	} else {
		return nil, nil
	}
}

// Bio is the resolver for the bio field.
func (r *userResolver) Bio(ctx context.Context, obj *db.User) (*string, error) {
	return &obj.Bio.String, nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *db.User) (model.UserRole, error) {
	return model.UserRole(obj.Role), nil
}

// Credits is the resolver for the credits field.
func (r *userResolver) Credits(ctx context.Context, obj *db.User) (float64, error) {
	if !validation.IsUserExists(obj) {
		return 0, nil
	} else {
		return r.Service.GetCreditsByUserID(ctx, obj.ID)
	}
}

// ConnectionStatus is the resolver for the connectionStatus field.
func (r *userResolver) ConnectionStatus(ctx context.Context, obj *db.User) (*int, error) {
	return r.Service.GetConnectionStatus(ctx, obj.ID)
}

// FollowingCount is the resolver for the followingCount field.
func (r *userResolver) FollowingCount(ctx context.Context, obj *db.User) (int64, error) {
	return r.Service.GetConnectionCount(ctx, obj.ID, constants.Following)
}

// FollowersCount is the resolver for the followersCount field.
func (r *userResolver) FollowersCount(ctx context.Context, obj *db.User) (int64, error) {
	return r.Service.GetConnectionCount(ctx, obj.ID, constants.Followers)
}

// FollowRequestsCount is the resolver for the followRequestsCount field.
func (r *userResolver) FollowRequestsCount(ctx context.Context, obj *db.User) (int64, error) {
	return r.Service.GetConnectionCount(ctx, obj.ID, constants.Requests)
}

// PostsCount is the resolver for the postsCount field.
func (r *userResolver) PostsCount(ctx context.Context, obj *db.User) (int64, error) {
	return r.Service.GetPostsCount(ctx, obj.ID)
}

// Node is the resolver for the node field.
func (r *usersEdgeResolver) Node(ctx context.Context, obj *model.UsersEdge) (*db.User, error) {
	return r.Service.GetUserByID(ctx, obj.Node.ID)
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

// UsersEdge returns generated.UsersEdgeResolver implementation.
func (r *Resolver) UsersEdge() generated.UsersEdgeResolver { return &usersEdgeResolver{r} }

type userResolver struct{ *Resolver }
type usersEdgeResolver struct{ *Resolver }
