package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/plogto/core/db"
	"github.com/plogto/core/graph/generated"
	"github.com/plogto/core/graph/model"
)

// EditUserSettings is the resolver for the editUserSettings field.
func (r *mutationResolver) EditUserSettings(ctx context.Context, input model.EditUserSettingsInput) (*db.User, error) {
	return r.Service.EditUserSettings(ctx, input)
}

// RepliesVisible is the resolver for the repliesVisible field.
func (r *userSettingsResolver) RepliesVisible(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.RepliesVisible), nil
}

// MediaVisible is the resolver for the mediaVisible field.
func (r *userSettingsResolver) MediaVisible(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.MediaVisible), nil
}

// LikesVisible is the resolver for the likesVisible field.
func (r *userSettingsResolver) LikesVisible(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.LikesVisible), nil
}

// RepliesVisibleForCurrentUser is the resolver for the repliesVisibleForCurrentUser field.
func (r *userSettingsResolver) RepliesVisibleForCurrentUser(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.RepliesVisibleForCurrentUser), nil
}

// MediaVisibleForCurrentUser is the resolver for the mediaVisibleForCurrentUser field.
func (r *userSettingsResolver) MediaVisibleForCurrentUser(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.MediaVisibleForCurrentUser), nil
}

// LikesVisibleForCurrentUser is the resolver for the likesVisibleForCurrentUser field.
func (r *userSettingsResolver) LikesVisibleForCurrentUser(ctx context.Context, obj *db.UserSettings) (model.UserSettingValue, error) {
	return model.UserSettingValue(obj.LikesVisibleForCurrentUser), nil
}

// UserSettings returns generated.UserSettingsResolver implementation.
func (r *Resolver) UserSettings() generated.UserSettingsResolver { return &userSettingsResolver{r} }

type userSettingsResolver struct{ *Resolver }
